package main

import "fmt"

//Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million,
//find the sum of the even-valued terms.

func main() {
	var x []int
	var sum int
	fn := fibonacci()
	for i := 0; i < 50; i++ {
		x = append(x, fn())
	}

	for _, a := range x {
		if a%2 == 0 && a < 4000000 {
			sum += a
		}
	}

	fmt.Println(sum)
}

func fibonacci() func() int {
	a, b := -1, 1
	return func() int {
		a, b = b, a+b
		return b
	}
}
